"""create initial database schema

Revision ID: 88ef79a677c4
Revises: 
Create Date: 2025-11-06 19:03:20.079348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ef79a677c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('initial_stock', sa.Integer(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("product_type IN ('single', 'set')", name='valid_product_type'),
    sa.CheckConstraint('current_stock >= 0', name='non_negative_stock'),
    sa.CheckConstraint('sale_price >= 0', name='positive_sale_price'),
    sa.CheckConstraint('unit_cost >= 0', name='positive_unit_cost'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_products_type', 'products', ['product_type'], unique=False)
    op.create_index('idx_products_created_at', 'products', ['created_at'], unique=False)
    op.create_table('sales_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.CheckConstraint('total_amount >= 0', name='positive_total_amount'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sales_history_timestamp', 'sales_history', ['timestamp'], unique=False)
    op.create_table('sale_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('quantity > 0', name='positive_quantity'),
    sa.CheckConstraint('subtotal >= 0', name='positive_subtotal'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales_history.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sale_items_sale_id', 'sale_items', ['sale_id'], unique=False)
    op.create_index('idx_sale_items_product_id', 'sale_items', ['product_id'], unique=False)
    op.create_table('set_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('set_product_id', sa.UUID(), nullable=False),
    sa.Column('item_product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='positive_quantity'),
    sa.ForeignKeyConstraint(['item_product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['set_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('set_product_id', 'item_product_id', name='unique_set_item_combination')
    )
    op.create_index('idx_set_items_set_product', 'set_items', ['set_product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_set_items_set_product', table_name='set_items')
    op.drop_table('set_items')
    op.drop_index('idx_sale_items_product_id', table_name='sale_items')
    op.drop_index('idx_sale_items_sale_id', table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index('idx_sales_history_timestamp', table_name='sales_history')
    op.drop_table('sales_history')
    op.drop_index('idx_products_created_at', table_name='products')
    op.drop_index('idx_products_type', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
